### ISSUE TITLE
Implicit Price Deflators for GDP changed

### ISSUE THREAD

**Issue by myParakeet** [USEPA/scghg#5]
https://github.com/USEPA/scghg/blame/f0c2b31837797cbb97bc5163b13c661de3f63d87/Meta-Analysis/code/estimate_meta_analysis_scghg.jl#L74C27-L74C41

This value has changed slightly. As of 2024-07-25: = 105.381/81.556

**Comment by bryanparthum** [comment]
Thanks @myParakeet! For now we plan to keep this repository as a replication for the numbers in the [EPA 2023 Report](https://www.epa.gov/system/files/documents/2023-12/epa_scghg_2023_report_final.pdf). If we transition to a new version we will be sure to consider this update. Thanks again for the issue!
